framework:
    mailer:
        envelope:
            sender: '%env(MAILER_SENDER)%'
        headers:
            From: 'admin <%env(MAILER_SENDER)%>'
            X-Custom-Header: 'foobar'
        dsn: '%env(MAILER_DSN)%'